// Reference tests for the CEDARS numeric core (calc.js) — fixed inputs, known outputs.
// These pin the production scoring, rating, carbon-intensity, and cost logic so results can't
// drift silently. Expected values were generated by running calc.js directly. Run: `npm test`.
import { describe, it, expect } from 'vitest';
import {
  cedarsScore, cedarsRating, getCI, getPrice, currencySym,
  CEDARS_DEPT_LO, CEDARS_DEPT_HI, CEDARS_AIUSE_LO, CEDARS_AIUSE_HI,
} from './calc.js';

describe('CEDARS Score — log-scale 0–100', () => {
  it('anchors: lo → 100, hi → 0', () => {
    expect(cedarsScore(CEDARS_DEPT_LO, CEDARS_DEPT_LO, CEDARS_DEPT_HI)).toBe(100);
    expect(cedarsScore(CEDARS_DEPT_HI, CEDARS_DEPT_LO, CEDARS_DEPT_HI)).toBe(0);
  });
  it('geometric midpoint of the anchors → 50', () => {
    const g = Math.sqrt(CEDARS_DEPT_LO * CEDARS_DEPT_HI);
    expect(cedarsScore(g, CEDARS_DEPT_LO, CEDARS_DEPT_HI)).toBe(50);
  });
  it('fixed reference points', () => {
    expect(cedarsScore(1.0, CEDARS_DEPT_LO, CEDARS_DEPT_HI)).toBe(57);   // department: 1 kgCO₂e/study
    expect(cedarsScore(4.0, CEDARS_AIUSE_LO, CEDARS_AIUSE_HI)).toBe(43); // AI label: 4 gCO₂e/study
  });
  it('clamps out-of-range and non-numeric input', () => {
    expect(cedarsScore(-5, 0.1, 20)).toBe(100);    // ≤ lo
    expect(cedarsScore(1000, 0.1, 20)).toBe(0);     // ≥ hi
    expect(cedarsScore('abc', 0.1, 20)).toBe(100);  // NaN → 0 → ≤ lo
  });
});

describe('CEDARS Rating — equal-quintile leaf bands (80/60/40/20)', () => {
  it('band boundaries map to the correct leaf count', () => {
    expect(cedarsRating(80).leaves).toBe(5);
    expect(cedarsRating(79).leaves).toBe(4);
    expect(cedarsRating(60).leaves).toBe(4);
    expect(cedarsRating(59).leaves).toBe(3);
    expect(cedarsRating(40).leaves).toBe(3);
    expect(cedarsRating(20).leaves).toBe(2);
    expect(cedarsRating(0).leaves).toBe(1);
  });
});

describe('Carbon intensity — getCI', () => {
  it('returns the regional default', () => {
    expect(getCI('France')).toBe(0.06);
    expect(getCI('Global average')).toBe(0.473);
  });
  it('uses the custom value only for "Editable custom"', () => {
    expect(getCI('Editable custom', '0.5')).toBe(0.5);
    expect(getCI('Editable custom', 'abc')).toBe(0.30); // NaN → default
  });
  it('falls back for an unknown region', () => {
    expect(getCI('Nowhere')).toBe(0.25);
  });
});

describe('Electricity price — getPrice / currencySym', () => {
  it('regional default, overridden only by a positive value', () => {
    expect(getPrice('Germany', '')).toBe(0.28);
    expect(getPrice('France', '0.9')).toBe(0.9);
    expect(getPrice('France', '0')).toBe(0.23); // 0 is not a positive override
  });
  it('currency symbol per region', () => {
    expect(currencySym('United States')).toBe('$');
    expect(currencySym('Germany')).toBe('€');
  });
});
