// Reference tests for the department calculation engine (model.js) — a fixed equipment fleet
// with fixed settings, pinned to known outputs so the core carbon/energy/cost math can't drift
// silently. Expected values were generated by running model.js directly and cross-checked by
// hand (e.g. imaging scans = Σ(unit scans × count) × 12; travel = scans × 20 km × 0.17 kg/km).
// Run: `npm test`.
import { describe, it, expect } from 'vitest';
import { buildFleet, computeDashboard, computeInterventions } from './model.js';

// One reference department: 2 CT, 1 MRI 1.5T, 3 Radiography, 2 Ultrasound, 1 PACS, 5 workstations.
const FLEET = { ct: 2, mri_15t: 1, xray: 3, ultrasound: 2, pacs: 1, workstations: 5 };

describe('buildFleet — scales specs by count', () => {
  const f = buildFleet(FLEET);
  it('one row per non-zero device (zero-count devices dropped)', () => {
    expect(f).toHaveLength(6);
    expect(f.some(r => r.modality === 'PET-CT')).toBe(false); // count 0 → excluded
  });
  it('power and scan volume scale linearly with count', () => {
    const ct = f.find(r => r.modality === 'CT');
    expect(ct.name).toBe('2× CT Scanner');
    expect(ct.active_kw).toBe(120); // 60 kW × 2
    expect(ct.idle_kw).toBe(16);    // 8 kW × 2
    expect(ct.scans).toBe(3600);    // 1800 × 2
  });
});

describe('computeDashboard — FLEET, Germany, Annual', () => {
  const d = computeDashboard('Germany', 'Annual', FLEET);
  it('imaging scans = Σ(unit scans × count) × 12', () => {
    expect(d.scopes.imagingScans).toBe(205200); // (2·1800 + 1000 + 3·2500 + 2·2500) × 12
  });
  it('total energy, carbon, and energy-per-scan', () => {
    expect(d.totals.kwh).toBeCloseTo(1037167.92, 2);
    expect(d.totals.co2Kg).toBeCloseTo(373380.45, 1);
    expect(d.totals.energyPerScan).toBeCloseTo(5.054, 3); // kWh ÷ scans
  });
  it('carbon = total energy × Germany grid intensity (0.36 kgCO₂e/kWh)', () => {
    expect(d.totals.co2Kg).toBeCloseTo(d.totals.kwh * 0.36, 0);
  });
  it('GHG scopes: Scope 2 = operational carbon; Scope 3 travel = scans × 20 km × 0.17 kg/km', () => {
    expect(d.scopes.scope2Kg).toBeCloseTo(373380.45, 1);
    expect(d.scopes.scope3TravelKg).toBe(697680); // 205200 × 20 × 0.17
  });
  it('Scope 3 embodied scales with the unit count of each device type', () => {
    // Σ EMBODIED_KG_MO[modality] × count × 12: (139·2 + 389·1 + 33·3 + 12·2 + 30·1 + 5·5) × 12
    expect(d.scopes.scope3EmbKg).toBe(10140);
  });
});

describe('computeDashboard — embodied carbon per unit', () => {
  it('four CT scanners embody 4× a single CT (not 1×)', () => {
    const one = computeDashboard('Germany', 'Monthly', { ct: 1 }).scopes.scope3EmbKg;
    const four = computeDashboard('Germany', 'Monthly', { ct: 4 }).scopes.scope3EmbKg;
    expect(one).toBe(139);
    expect(four).toBe(556); // 139 × 4
  });
});

describe('computeInterventions — FLEET, delta from current config', () => {
  it('two operational levers stack additively on energy', () => {
    const iv = computeInterventions(
      ['Turn MRI/CT scanners off overnight', 'Reduce low-value imaging'],
      'Germany', 'Annual', FLEET, undefined, 'AWS', 'Standby', {});
    expect(iv.count).toBe(2);
    expect(iv.baseline.kwh).toBeCloseTo(1037167.92, 2);
    expect(iv.savings.kwh).toBe(34080);              // overnight 24480 + low-value 9600
    expect(iv.projected.kwh).toBeCloseTo(1003087.92, 2);
    expect(iv.savings.pctEnergy).toBeCloseTo(3.3, 1);
  });
  it('storage axial-only lever saves the reformats delta vs current all-reformats config', () => {
    const iv = computeInterventions(
      ['Store only acquired axial series (avoid reformats)'],
      'Germany', 'Annual', FLEET, undefined, 'Local compute', 'Standby',
      { reformats: 'all', cloud: false, retentionYears: 10 });
    expect(iv.savings.kwh).toBe(108864);
    expect(iv.savings.pctEnergy).toBeCloseTo(10.5, 1);
  });
  it('no levers selected → zero savings, projection equals baseline', () => {
    const iv = computeInterventions([], 'Germany', 'Annual', FLEET, undefined, 'Local compute', 'Standby', {});
    expect(iv.count).toBe(0);
    expect(iv.savings.kwh).toBe(0);
    expect(iv.projected.kwh).toBeCloseTo(iv.baseline.kwh, 2);
  });
});

// Measured-data overrides (active_kw/idle_kw/standby_kw/off_kw/scans per device, and a custom
// storage kWh/TB/yr) — the "Advanced equipment parameters" mechanism. Blank/absent fields keep
// the EQUIPMENT_UNITS literature default; only fields explicitly set in `overrides` change.
describe('buildFleet — per-device overrides', () => {
  it('an overridden field replaces the default (post-count-scaling); untouched fields and count scaling are unaffected', () => {
    const f = buildFleet({ ct: 2 }, { ct: { active_kw: 45 } });
    expect(f[0].active_kw).toBe(90);  // 45 kW × 2 units, not the 60 kW default
    expect(f[0].idle_kw).toBe(16);    // untouched field: 8 kW default × 2 units
    expect(f[0].overridden).toBe(true);
  });
  it('no override for a device → overridden is falsy, values equal the plain default', () => {
    const f = buildFleet({ ct: 2 });
    expect(f[0].overridden).toBeFalsy();
    expect(f[0].active_kw).toBe(120); // 60 kW default × 2
  });
});

describe('computeDashboard — override effects on confidence, scans, and storage', () => {
  it('an overridden row is flagged confidence:"measured"; untouched rows stay "estimated"', () => {
    const d = computeDashboard('Germany', 'Monthly', { ct: 1, workstations: 1 }, undefined, {}, {}, { ct: { active_kw: 45 } });
    expect(d.byEquipment.find(r => r.modality === 'CT').confidence).toBe('measured');
    expect(d.byEquipment.find(r => r.modality === 'Workstation').confidence).toBe('estimated');
  });
  it('overriding scans (study volume) changes imagingScans and the storage archive size', () => {
    const dDefault  = computeDashboard('Germany', 'Monthly', { ct: 1 });
    const dOverride = computeDashboard('Germany', 'Monthly', { ct: 1 }, undefined, {}, {}, { ct: { scans: 900 } });
    expect(dDefault.scopes.imagingScans).toBe(1800);
    expect(dOverride.scopes.imagingScans).toBe(900); // half the default 1800 scans/month
  });
  it('a custom storage intensity fully overrides the on-prem/cloud default, scaling storage kWh proportionally', () => {
    const dCustom  = computeDashboard('Germany', 'Annual', { ct: 5 }, undefined, {}, { intensityCustom: 1000 });
    const dDefault = computeDashboard('Germany', 'Annual', { ct: 5 }, undefined, {}, {}); // on-prem default 600
    expect(dCustom.storage.intensity).toBe(1000);
    expect(dDefault.storage.intensity).toBe(600);
    expect(dCustom.storage.kwh).toBeCloseTo(dDefault.storage.kwh * (1000 / 600), 1);
  });
});

describe('computeInterventions — overrides flow into the baseline used for savings', () => {
  it('baseline.kwh matches computeDashboard totals under the same overrides', () => {
    const overrides = { ct: { active_kw: 45 } };
    const base = computeDashboard('Germany', 'Annual', FLEET, undefined, {}, {}, overrides);
    const iv   = computeInterventions([], 'Germany', 'Annual', FLEET, undefined, 'Local compute', 'Standby', {}, overrides);
    expect(iv.baseline.kwh).toBeCloseTo(base.totals.kwh, 2);
  });
});
